from dataclasses import dataclass, field

UNITED_STATES_GEOGRAPHY = {
    "New York": ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island", "Williamsburg", "Harlem"],
    "Los Angeles": ["Hollywood", "Santa Monica", "Beverly Hills", "Downtown LA", "Venice", "Silver Lake", "Pasadena"],
    "Chicago": ["Loop", "Lincoln Park", "Hyde Park", "Wicker Park", "Bronzeville", "Lakeview", "Logan Square"],
    "Houston": ["Downtown", "Uptown", "The Heights", "Midtown", "Galleria", "Montrose", "Museum District"],
    "Phoenix": ["Downtown", "Scottsdale", "Tempe", "Mesa", "Glendale", "Chandler", "Paradise Valley"],
    "Philadelphia": ["Center City", "South Philly", "West Philly", "Northern Liberties", "Fishtown", "University City", "Chestnut Hill"],
    "San Antonio": ["Downtown", "Alamo Heights", "Stone Oak", "Southtown", "Pearl District", "King William", "Monte Vista"],
    "San Diego": ["Gaslamp Quarter", "La Jolla", "Pacific Beach", "North Park", "Hillcrest", "Little Italy", "Encinitas"],
    "Dallas": ["Uptown", "Deep Ellum", "Oak Cliff", "Bishop Arts", "Downtown", "Lakewood", "Knox-Henderson"],
    "San Francisco": ["Mission", "Hayes Valley", "North Beach", "SoMa", "Marina", "Haight-Ashbury", "Pacific Heights"],
    "Austin": ["Downtown", "South Congress", "East Austin", "Zilker", "Mueller", "West Lake Hills", "Bouldin Creek"],
    "Jacksonville": ["Downtown", "Jacksonville Beaches", "San Marco", "Riverside", "Avondale", "Southside", "Mandarin"],
    "Fort Worth": ["Downtown", "West 7th", "Magnolia Avenue", "Stockyards", "Cultural District", "TCU Area", "Fossil Creek"],
    "Columbus": ["Downtown", "Short North", "German Village", "Clintonville", "Grandview Heights", "Upper Arlington", "Franklinton"],
    "Charlotte": ["Uptown", "South End", "Plaza Midwood", "NoDa", "Dilworth", "Myers Park", "Ballantyne"],
    "Indianapolis": ["Downtown", "Broad Ripple", "Mass Ave", "Fountain Square", "Meridian-Kessler", "Butler-Tarkington", "Irvington"],
    "Seattle": ["Downtown", "Capitol Hill", "Ballard", "Queen Anne", "Fremont", "West Seattle", "Belltown"],
    "Denver": ["Downtown", "LoHi", "Cherry Creek", "Capitol Hill", "Highlands", "Washington Park", "RiNo"],
    "Washington DC": ["Dupont Circle", "Georgetown", "Adams Morgan", "Capitol Hill", "U Street", "Shaw", "Navy Yard"],
    "Boston": ["Back Bay", "South End", "North End", "Beacon Hill", "Allston", "Cambridge", "Somerville"],
    "El Paso": ["Downtown", "Sunset Heights", "Kern Place", "Upper Valley", "Westside", "Mission Valley", "Manhattan Heights"],
    "Detroit": ["Downtown", "Midtown", "Corktown", "Greektown", "New Center", "West Village", "Eastern Market"],
    "Nashville": ["Downtown", "East Nashville", "Gulch", "West End", "12 South", "Green Hills", "Germantown"],
    "Memphis": ["Downtown", "Midtown", "Cooper-Young", "East Memphis", "Hickory Hill", "South Main", "Mud Island"],
    "Portland": ["Pearl District", "Alberta", "Hawthorne", "Mississippi Avenue", "Downtown", "Division Street", "Northwest District"],
    "Oklahoma City": ["Downtown", "Bricktown", "Midtown", "Paseo", "Uptown 23rd", "Classen Curve", "Western Avenue"],
    "Las Vegas": ["Strip", "Downtown", "Summerlin", "Henderson", "Boulder City", "Centennial Hills", "Spring Valley"],
    "Louisville": ["Downtown", "Highlands", "St. Matthews", "Old Louisville", "Germantown", "Nulu", "Crescent Hill"],
    "Baltimore": ["Inner Harbor", "Fell's Point", "Canton", "Mount Vernon", "Hamden", "Federal Hill", "Patterson Park"],
    "Milwaukee": ["Downtown", "Third Ward", "Bay View", "East Side", "Riverwest", "Walker's Point", "Brewer's Hill"],
    "Albuquerque": ["Downtown", "Nob Hill", "Old Town", "North Valley", "Westside", "Uptown", "Rio Rancho"],
    "Tucson": ["Downtown", "Fourth Avenue", "Sam Hughes", "Oro Valley", "Casas Adobes", "Starr Pass", "Tanque Verde"],
    "Fresno": ["Downtown", "Fresno High", "Fig Garden", "Clovis", "Sunnyside", "North Fresno", "Tower District"],
    "Sacramento": ["Downtown", "Midtown", "Land Park", "East Sacramento", "Tahoe Park", "Oak Park", "Natomas"],
    "Kansas City": ["Downtown", "Plaza", "Crossroads", "Westport", "Brookside", "River Market", "Country Club"],
    "Miami": ["South Beach", "Downtown", "Brickell", "Coral Gables", "Wynwood", "Little Havana", "Coconut Grove"],
    "Atlanta": ["Buckhead", "Midtown", "Old Fourth Ward", "Virginia-Highland", "Inman Park", "West End", "East Atlanta"],
    "Raleigh": ["Downtown", "North Hills", "Cameron Village", "Five Points", "Warehouse District", "Glenwood South", "Brier Creek"],
    "Cleveland": ["Downtown", "Ohio City", "Tremont", "Gordon Square", "University Circle", "Little Italy", "Detroit-Shoreway"],
    "Tampa": ["Downtown", "Ybor City", "Hyde Park", "South Tampa", "Westshore", "Channelside", "Seminole Heights"],
    "San Jose": ["Downtown", "Willow Glen", "Santana Row", "Almaden Valley", "Evergreen", "Rose Garden", "North San Jose"],
    "New Orleans": ["French Quarter", "Garden District", "Marigny", "Warehouse District", "Treme", "Uptown", "Algiers"],
    "Pittsburgh": ["Downtown", "Shadyside", "Lawrenceville", "Squirrel Hill", "Oakland", "Mount Washington", "South Side"],
    "Minneapolis": ["Downtown", "Uptown", "Northeast", "Dinkytown", "North Loop", "Loring Park", "Warehouse District"],
    "St. Louis": ["Central West End", "Soulard", "The Hill", "Midtown", "Tower Grove", "Lafayette Square", "Clayton"],
    "Salt Lake City": ["Downtown", "Sugar House", "Avenues", "Capitol Hill", "Liberty Wells", "Rose Park", "Millcreek"],
    "Boulder": ["Downtown", "Pearl Street Mall", "University Hill", "North Boulder", "South Boulder", "Gunbarrel", "Table Mesa"],
    "Providence": ["Downtown", "Fox Point", "College Hill", "West End", "Elmhurst", "Mount Hope", "Olneyville"],
    "Charleston": ["Downtown", "French Quarter", "South of Broad", "West Ashley", "Mount Pleasant", "Harleston Village", "Mazyck-Wragg"],
    "Honolulu": ["Waikiki", "Downtown", "Manoa", "Kaimuki", "Kahala", "Pearl City", "Kapolei"]
}



UNITED_KINGDOM_GEOGRAPHY = {

    "London": ["Camden", "Greenwich", "Kensington", "Shoreditch", "Soho", "Mayfair", "Brixton", "South Bank", "Hackney", "Islington"],
    "Birmingham": ["City Centre", "Edgbaston", "Balsall Heath", "Digbeth", "Sparkhill", "Moseley", "Sutton Coldfield", "Handsworth", "Harborne"],
    "Manchester": ["City Centre", "Salford", "Chorlton", "Northern Quarter", "Fallowfield", "West Didsbury", "Ancoats", "Trafford", "Levenshulme"],
    "Glasgow": ["City Centre", "West End", "Southside", "Merchant City", "Dennistoun", "Partick", "Finnieston", "Castlemilk", "Hyndland"],
    "Edinburgh": ["Old Town", "New Town", "Leith", "Stockbridge", "Morningside", "Marchmont", "Bruntsfield", "Craiglockhart", "Portobello"],
    "Liverpool": ["City Centre", "Toxteth", "Woolton", "Allerton", "Wavertree", "Kensington", "Aigburth", "Garston", "Kirkdale"],
    "Bristol": ["City Centre", "Clifton", "Bedminster", "Stokes Croft", "Southville", "Montpelier", "Redland", "Brislington", "Easton"],
    "Cardiff": ["City Centre", "Cardiff Bay", "Pontcanna", "Cathays", "Roath", "Penarth", "Whitchurch", "Grangetown", "Riverside"],
    "Leeds": ["City Centre", "Headingley", "Roundhay", "Moortown", "Chapel Allerton", "Bramley", "Armley", "Horsforth", "Otley"],
    "Sheffield": ["City Centre", "Ecclesall", "Crookes", "Hillsborough", "Nether Edge", "Broomhill", "Kelham Island", "Attercliffe", "Darnall"],
    "Newcastle": ["City Centre", "Quayside", "Jesmond", "Heaton", "Gosforth", "Ouseburn", "Sandyford", "Byker", "Elswick"],
    "Nottingham": ["City Centre", "West Bridgford", "Mapperley", "Sherwood", "Beeston", "Lace Market", "The Park", "Hyson Green", "Clifton"],
    "Belfast": ["City Centre", "Cathedral Quarter", "Botanic Avenue", "Titanic Quarter", "South Belfast", "East Belfast", "West Belfast", "Ballynafeigh", "Ormeau"],
    "Brighton": ["City Centre", "Kemptown", "Hove", "Hanover", "Preston Park", "Seven Dials", "North Laine", "Queen's Park", "Lewes Road"],
    "Southampton": ["City Centre", "Ocean Village", "Portswood", "Bassett", "Shirley", "Eastleigh", "Woolston", "Bitterne", "Millbrook"],
    "Derby": ["City Centre", "Darley Abbey", "Littleover", "Mickleover", "Spondon", "Cathedral Quarter", "West End", "Chaddesden", "Oakwood"],
    "Plymouth": ["City Centre", "Barbican", "Mutton Cove", "Keyham", "Derriford", "Peverell", "Stoke", "Devonport", "Crownhill"],
    "Wolverhampton": ["City Centre", "Tettenhall", "Bilston", "Wednesfield", "Compton", "Penn", "Whitmore Reans", "Heath Town", "Chapel Ash"],
    "Leicester": ["City Centre", "Belgrave", "Oadby", "St. Matthew's", "Birstall", "Crown Hills", "Glenfield", "Clarendon Park", "Aylestone"],
    "Cambridge": ["City Centre", "Mill Road", "Newnham", "Arbury", "Fen Ditton", "Chesterton", "Trumpington", "West Cambridge", "Eddington"],
    "Oxford": ["City Centre", "Headington", "Cowley", "Summertown", "Jericho", "Marston", "Wolvercote", "Botley", "Kennington"],
    "Stoke-on-Trent": ["City Centre", "Hanley", "Fenton", "Stoke", "Longton", "Burslem", "Tunstall", "Trentham", "Meir"],
    "Coventry": ["City Centre", "Earlsdon", "Canley", "Allesley", "Finham", "Cheylesmore", "Coundon", "Wyken", "Stoke"],
    "Bradford": ["City Centre", "Saltaire", "Haworth", "Ilkley", "Keighley", "Manningham", "Great Horton", "Butterfield", "Shipley"],
    "York": ["City Centre", "Micklegate", "Monkbar", "The Shambles", "Bishophill", "Clifton", "Heworth", "Fulford", "Dringhouses"],
    "Exeter": ["City Centre", "St. Leonard's", "Exwick", "St. Thomas", "Topsham", "Heavitree", "Mount Pleasant", "Polsloe", "Wonford"],
    "Norwich": ["City Centre", "Golden Triangle", "Norwich Lanes", "Thorpe Hamlet", "Pockthorpe", "Eaton", "New Sprowston", "Cathedral Quarter", "Old Lakenham"],
    "Bournemouth": ["Town Centre", "Boscombe", "Westbourne", "Southbourne", "Winton", "Moordown", "Charminster", "Christchurch", "Poole"],
    "Sunderland": ["City Centre", "Roker", "Seaburn", "Hendon", "Grangetown", "Ford Estate", "Ashbrooke", "Plains Farm", "Thornhill"],
    "Luton": ["Town Centre", "Bury Park", "Wardown", "Leagrave", "Sundon Park", "Stopsley", "Limbury", "Lewisham", "Bramingham"],
    "Reading": ["Town Centre", "Caversham", "Tilehurst", "Whitley", "Woodley", "Earley", "Dee Park", "Coley", "Southcote"],
    "Swansea": ["City Centre", "Brynhyfryd", "Uplands", "Mumbles", "Cwmbwrla", "Townhill", "Port Talbot", "Morriston", "Mumbles"],
    "Aberdeen": ["City Centre", "West End", "Dyce", "Cults", "Rosemount", "Borrowstounness", "Shire", "Kingswells", "Balgownie"],
    "Dundee": ["City Centre", "Hilltown", "Strathmartine", "Broughty Ferry", "Blackness", "Lochee", "Troshaven", "Barnhill", "Douglas"],
    "Gloucester": ["City Centre", "Kingsholm", "Tuffley", "Longlevens", "Abbeymead", "Poddsmead", "Hempsted", "Barnwood", "Matson"],
    "Cheltenham": ["Town Centre", "Leckhampton", "Pittville", "Charlton Kings", "Prettion", "All Saints", "St. Mark's", "Swindon Village", "Bredon"],
    "Kingston upon Hull": ["City Centre", "Avenues", "Willerby", "Kingswood", "Brough", "Sutton", "Newland", "Beverley", "Anlaby"],
    "Blackpool": ["Town Centre", "North Shore", "South Shore", "Central Pier", "Bispham", "Poulton-le-Fylde", "Fleetwood", "Cleveleys", "Lytham"],
    "Middlesbrough": ["Town Centre", "Acklam", "Normanby", "Marton", "Couby Newham", "Brambles Farm", "Hemlington", "Thorntree", "Pallister"],
    "Swindon": ["Town Centre", "Old Town", "Stratton", "Walcot", "Gorse Hill", "Penhill", "Farleigh", "Westlea", "Rodbourne"],
    "Milton Keynes": ["City Centre", "Central MK", "Furzton", "Woughton", "Stony Stratford", "Bletchley", "Crownhill", "Walnut Tree", "Eaglestone"],
    "Perth": ["City Centre", "Balhousie", "Bridgend", "Inveralmond", "Letham", "Tulloch", "Muirton", "Burghmuir", "Glenearn"],
    "St. Albans": ["City Centre", "Verulamium", "The Camp", "St. Stephen's", "London Colney", "Sandridge", "Wheathampstead", "Harpenden", "Colney Heath"],
    "Woking": ["Town Centre", "Knaphill", "Mayford", "Westfield", "Horsell", "Byfleet", "Sutton Green", "Brookwood", "Lightwater"],
    "Leamington Spa": ["Town Centre", "North Leamington", "Old Town", "Radford Semele", "Cubbington", "Whitnash", "Bishop's Tachbrook", "Warwick Gates", "Lillington"],
    "Inverness": ["City Centre", "Crown", "Merkinch", "Hilton", "Dalneigh", "Kinmylies", "Charleston", "Smithton", "Culloden"],
    "Londonderry": ["City Centre", "Waterside", "Bogside", "Creggan", "Shantallow", "Gobnascale", "Eglinton", "Strathfoyle", "Clondermot"],
    "Aberystwyth": ["Town Centre", "North Parade", "Penparcau", "Llanbadarn", "Waunfawr", "Trefechan", "Morfa", "Blaenplwyf", "Capel Dewi"],
    "Bangor": ["City Centre", "Upper Bangor", "Hirael", "Menai", "Beaumaris", "Llandygai", "Tregarth", "Bethesda", "Port Dinorwic"],
    "Bath": ["City Centre", "Widcombe", "Larkhall", "Walcot", "Bathwick", "Twerton", "Bear Flat", "Oldfield Park", "Combe Down"],
    "Bury St Edmunds": ["Town Centre", "Westgate", "Eastgate", "Risbygate", "Howard Estate", "Tollgate", "Moreton Hall", "Haverhill Road"],
    "Canterbury": ["City Centre", "Dane Valley", "St. Dunstan's", "St. Stephen's", "Hales Place", "Blean", "Chartham", "Sturry", "Wingham"],
    "Carlisle": ["City Centre", "Stanwix", "Edentown", "Morton", "Raffles", "Harraby", "Belle Vue", "Burgh-by-Sands", "Dalston"],
    "Chester": ["City Centre", "Handbridge", "Hoole", "Upton", "Boughton", "Frodsham", "Ellesmere Port", "Tarvin", "Helsby"],
    "Chichester": ["City Centre", "East Row", "West Row", "North Street", "Southgate", "Donnington", "Boxgrove", "Aldwick", "Selsey"],
    "Colchester": ["City Centre", "Lexden", "Mile End", "Shrub End", "Greenstead", "Old Heath", "Wivenhoe", "Rowhedge", "Berechurch"],
    "Durham": ["City Centre", "Elvet", "Gilesgate", "Neville's Cross", "Crossgate", "Framwellgate Moor", "Pity Me", "Bearpark", "Sacriston"],
    "Ely": ["City Centre", "Lansdowne", "The Stannary", "St. Mary's", "Chesterton", "Soham", "Littleport", "Fordham", "Burwell"],
    "Gloucester": ["City Centre", "Kingsholm", "Tuffley", "Longlevens", "Abbeymead", "Poddsmead", "Hempsted", "Barnwood", "Matson"],
    "Hereford": ["City Centre", "Holmer", "Belmont", "Tupsley", "Lower Bullingham", "Kings Acre", "Bromyard Road", "Haywood", "Lugwardine"],
    "Lichfield": ["City Centre", "Boley Park", "St. Michael's", "Chadsmead", "Curborough", "Whittington", "Fradley", "Alrewas", "Shenstone"],
    "Lincoln": ["City Centre", "Brayford Wharf", "Bailgate", "Newport", "Monks Road", "Waterside", "Canwick", "Bracebridge", "Waddington"],
    "Newport": ["City Centre", "Maindee", "Caerleon", "Malpas", "Ringland", "Bettws", "Rogerstone", "Risca", "Cwmbran"],
    "Peterborough": ["City Centre", "Cathedral Square", "Millfield", "Dogsthorpe", "Paston", "Werrington", "Gunthorpe", "Yaxley", "Hampton"],
    "Preston": ["City Centre", "Deepdale", "Ribbleton", "Fulwood", "Ashton-on-Ribble", "Lea", "Cottam", "Broughton", "Goosnargh"],
    "Ripon": ["City Centre", "North Street", "Park Street", "Ure Bank", "Bondgate", "Bishopton", "Littlethorpe", "Norton", "Hutton"],
    "Salisbury": ["City Centre", "Bemerton", "Harnham", "Laverstock", "Stratford-sub-Castle", "Old Sarum", "Alderbury", "Whiteparish", "Downton"],
    "Southwold": ["Town Centre", "Blackshore", "Blythburgh", "Walberswick", "Dunwich", "Wenhaston", "Uggeshall", "Bramfield", "Thorington"],
    "Truro": ["City Centre", "Highertown", "Kenwyn", "St. Clement", "Moresk", "Roscorla", "Newham", "Threemilestone", "Chacewater"],
    "Wakefield": ["City Centre", "Pontefract", "Castleford", "Normanton", "Ossett", "Horbury", "Knottingley", "Featherstone", "Hemsworth"],
    "Wells": ["City Centre", "Priory Wood", "Wookey", "St. Thomas", "Mendip", "Dinder", "Croscombe", "Pilton", "Glastonbury"],
    "Winchester": ["City Centre", "St. Bartholomew's", "St. Paul's", "St. Cross", "Hyde", "Fullerton", "Chilcomb", "Twyford", "Southwick"],
    "Worcester": ["City Centre", "St. John's", "Wichenford", "Powick", "Claines", "Warndon", "St. Peter's", "Upper Wick", "Sneachill"],
    "Ayr": ["Town Centre", "Newton-on-Ayr", "Whitletts", "Castlehill", "Broughton", "St. Leonard's", "Holmston", "Kincaidston", "Doonside"],
    "Dumfries": ["Town Centre", "Sandgate", "Loreburn", "Huntersfield", "Troqueer", "Newbridge", "Cargenbridge", "Auldgirth", "Thornhill"],
    "Dundee": ["City Centre", "Hilltown", "Strathmartine", "Broughty Ferry", "Blackness", "Lochee", "Troshaven", "Barnhill", "Douglas"],
    "East Kilbride": ["Town Centre", "Greenhills", "Westwood", "East Mains", "Calderwood", "Murray", "Earnock", "St. Leonard's", "Whitehills"],
    "Falkirk": ["Town Centre", "Laurencekirk", "Bainsford", "Camelon", "Brockville", "Stenhousemuir", "Larbert", "Plean", "Denny"],
    "Inverness": ["City Centre", "Crown", "Merkinch", "Hilton", "Dalneigh", "Kinmylies", "Charleston", "Smithton", "Culloden"],
    "Kilmarnock": ["Town Centre", "Grange", "Hurlford", "Kilmarnock Road", "Moorfield", "Crosshouse", "Gatehead", "Dundonald", "Troon"],
    "Kirkwall": ["Town Centre", "Westray", "St. Ola", "Hatston", "Lerwick", "Garth", "Orphir", "Stenness", "Firth"],
    "Paisley": ["Town Centre", "Ferguslie", "Charleston", "Glenburn", "Foxbar", "Johnstone", "Renfrew", "Linwood", "Bishopton"],
    "Stirling": ["City Centre", "Raploch", "Cornton", "St. Ninians", "Bannockburn", "Cambusbarron", "Bridge of Allan", "Killin", "Callander"],
    "Bangor (NI)": ["Town Centre", "Bryansburn", "Hillsborough", "Newtownards", "Holywood", "Groomsport", "Donaghadee", "Millisle", "Greyabbey"],
    "Coleraine": ["Town Centre", "Ballycastle", "Mountsandel", "University Quarter", "Portrush", "Portstewart", "Garvagh", "Killowen", "Dunluce"],
    "Derry": ["City Centre", "Waterside", "Bogside", "Creggan", "Shantallow", "Gobnascale", "Eglinton", "Strathfoyle", "Clondermot"],
    "Enniskillen": ["Town Centre", "Monea", "Erne", "Kesh", "Belleek", "Irvinestown", "Lisbellaw", "Rosslea", "Newtownbutler"],
    "Lisburn": ["City Centre", "Ballinderry", "Blaris", "Hillsborough", "Maze", "Moira", "Glenavy", "Crumlin", "Aldergrove"],
    "Newry": ["City Centre", "Dundalk Road", "Hill Street", "Canal Street", "Ballyholland", "Cloughoge", "Bessbrook", "Killeavy", "Forkhill"],
    "Omagh": ["Town Centre", "Castle Street", "Dublin Road", "Tattyreagh", "Dromore", "Fintona", "Dillstown", "Glenelly", "Sion Mills"],
    "Carlow": ["Town Centre", "Laois", "Tullow", "Ballon", "Rathvilly", "Palatine", "Castlecomer", "Goresbridge", "Myshall"],
    "Kilkenny": ["City Centre", "Butler District", "St. Canice", "Kells Road", "Loughboy", "Bennettsbridge", "Thomastown", "Ballyhale", "Gowran"],
    "Waterford": ["City Centre", "The Quays", "Ballybricken", "Glenmore", "Tramore", "Dungarvan", "Lismore", "Kilmacthomas", "Portlaw"],
    "Wexford": ["Town Centre", "Ferrybank", "Selskar", "Ballygeary", "Rosslare", "Enniscorthy", "Gorey", "Ferns", "Bunclody"],
    "Caernarfon": ["Town Centre", "Castlefield", "Dolbadarn", "Menai", "Waunfawr", "Bontnewydd", "Groeslon", "Llanberis", "Llanrug"],
    "Colwyn Bay": ["Town Centre", "Old Colwyn", "Rhos-on-Sea", "Llanddulas", "Conwy", "Penrhyn Bay", "Glan Conwy", "Trefriw", "Betws-y-Coed"],
    "Llanelli": ["Town Centre", "Bigyn", "Bynea", "Ffwrnes", "Llangennech", "Pontarddulais", "Gorseinon", "Loughor", "Llansamlet"],
    "Newport (Wales)": ["City Centre", "Maindee", "Caerleon", "Malpas", "Ringland", "Bettws", "Rogerstone", "Risca", "Cwmbran"],
    "Wrexham": ["City Centre", "Rhosddu", "Little Acton", "Hightown", "Cefn-y-Bedd", "Llay", "Brymbo", "Coedpoeth", "Ruabon"]
}


PAKISTAN_GEOGRAPHY = {
    "Karachi": ["Clifton", "Defence", "Gulshan-e-Iqbal", "Korangi", "Malir", "Nazimabad", "Saddar", "Landhi", "Shah Faisal", "Gulistan-e-Jauhar"],
    "Lahore": ["Gulberg", "Defence", "Johar Town", "Anarkali", "Model Town", "Garden Town", "Mall Road", "Ichhra", "Samnabad", "Railway Road"],
    "Islamabad": ["F-6", "F-7", "F-8", "G-6", "G-7", "G-8", "I-8", "E-7", "D-12", "Bahria Town"],
    "Rawalpindi": ["Saddar", "Cantonment", "Gulrez", "Westridge", "Chaklala", "Peshawar Road", "Shah Khalid", "Satellite Town", "Bagh Sardaran", "Liaquat Bagh"],
    "Faisalabad": ["Gulberg", "Madina Town", "Iqbal Town", "Jinnah Colony", "Kotwali", "Makhanwala", "Kashmir Road", "Peoples Colony", "Ghayal Road", "Tariqabad"],
    "Multan": ["Khidmat", "Shah Rukn-e-Alam", "Chowk Kumharan", "Yousuf Raza", "Gulgasht", "Shah Jamal", "Mausa", "Duniyapur", "Cantt", "Bosan Road"],
    "Peshawar": ["Saddar", "Hayatabad", "University Town", "Gulbahar", "Kohat Road", "Cantonment", "Nishtarabad", "Mian Ki", "Tahkal", "Hangu Road"],
    "Quetta": ["Zarghoon", "Jinnah Town", "Gulshan", "Mariabad", "Nawa Killi", "Airport Road", "University Road", "Killi Abdul", "Panjpair", "Jinnah Road"],
    "Sialkot": ["Cantonment", "Gulshan-i-Iqbal", "Ganpat", "Marar", "Allama Iqbal Road", "Kashmir Road", "Sadiq Canal", "Bhattiabad", "Muftiabad", "Gulistan Colony"],
    "Gujranwala": ["Cantonment", "Peoples Colony", "Model Town", "Gulshan Abad", "Chandu Talwala", "Satellite Town", "Jinnah Road", "Kashmir Road", "Bungalow Road", "Ali Pur"],
    "Bahawalpur": ["Model Town", "Gulberg", "New Housing Colony", "Satellite Town", "Cantonment", "Chowk Azam", "Hasilpur Road", "Ahmadpur", "Uch Sharif", "Dera Nawab"],
    "Sargodha": ["Cantonment", "Gulshan-e-Sargodha", "Model Town", "Satellite Town", "Ghaziabad", "Village Din", "Millat Road", "Kashmir Road", "Gulberg", "Quaid-e-Azam"],
    "Mingora": ["Khawaja Plaza", "Green Chowk", "Cantonment", "Pir Kalay", "Landikas", "Nawab Colony", "Saidu Sharif", "Kanju", "Fizagut", "Mingora Bazaar"],
    "Sukkur": ["Cantonment", "Shahdad Pur", "Pano Aqil", "Kandhkot", "Daharki", "Kashmore", "Rohri", "Arore", "Miryarpur", "Bhatti"],
    "Kasur": ["Cantonment", "Gulberg", "Model Town", "Satellite Town", "Rupo", "Kotli", "Chak No. 1", "Sarai Mughal", "Hijrat", "Kohali"],
    "Hyderabad": ["Latifabad", "Qasimabad", "Saddar", "Cantonment", "Gulistan", "Tando Bago", "Hirabad", "Bhitai Nagar", "Miran Shah", "Bambar"],
    "Larkana": ["Cantonment", "Chandka", "Gulshan-e-Larkana", "Rato Dero", "Dokri", "Bakrani", "Ratodero", "Sikandarabad", "Miro Khan", "Kamber"],
    "Nawabshah": ["Cantonment", "Model Town", "Kazi Ahmed", "Daulatpur", "Bandhi", "Sakrand", "Dadu", "Mori", "Aqil", "Lakhyar"],
    "Jhang": ["Cantonment", "Gulberg", "Satellite Town", "Kot Karam", "Shah Jewana", "Mandi", "Maghiana", "Madina", "Chak 41", "Marral"],
    "Chiniot": ["Cantonment", "Gulshan", "Pakpattan Road", "Lakhanwal", "Jhang Road", "Wazir", "Mandi Bahauddin", "Seraiki", "Kishan", "Ram"],
    "Okara": ["Cantonment", "Gulberg", "Renala Khurd", "Satellite Town", "Mandi", "Depalpur", "Basharat", "Hasan", "Ahmed", "Gulshan"],
    "Burewala": ["Cantonment", "Gulshan", "Quaid-e-Azam", "Mandi", "Sahiwal Road", "Chichawatni", "Vehari", "Kammar", "Makhdom", "Pandit"],
    "Mardan": ["Cantonment", "Gulbahar", "Mahmudabad", "Takhtbai", "Katlang", "Rustam", "Sheikh", "Regi", "Gulshan", "Khan"],
    "Abbottabad": ["Cantonment", "Gulshan", "Mandian", "Kakul", "Nathia Gali", "Thandiani", "Havelian", "Qalandarabad", "Bagh", "Jinnahabad"],
    "Gujrat": ["Cantonment", "Gulshan", "Khatib", "Madina", "Beowa", "Sukhi", "Bhody", "Kotla", "Mandi", "Chak"],
    "Rahim Yar Khan": ["Cantonment", "Gulberg", "Model Town", "Satellite Town", "Khanpur", "Liaquatpur", "Chak", "Sadiq", "Islam", "Iqbal"],
    "Sahiwal": ["Cantonment", "Gulshan", "Model Town", "Satellite Town", "Noorshah", "Marmandi", "Yousaf", "Zafar", "Riaz", "Khalid"],
    "Dera Ghazi Khan": ["Cantonment", "Gulshan", "Model Town", "Satellite Town", "Kot Mubarak", "Choti", "Kohlu", "Zindani", "Deen", "Sadiq"],
    "Muzaffargarh": ["Cantonment", "Gulshan", "Satellite Town", "Lakhi", "Khangi", "Jatoi", "Gurmani", "Sahab", "Habib", "Jalal"],
    "Turbat": ["Cantonment", "Gulshan", "Dasht", "Kech", "Hoshab", "Mand", "Suntsar", "Gabd", "Kalar", "Chak"],
    "Sibi": ["Cantonment", "Gulshan", "Quetta Road", "Kakar", "Mari", "Mithri", "Lakhan", "Dera", "Adam", "Rustam"],
    "Ghotki": ["Cantonment", "Gulshan", "Mirpur", "Daharki", "Ubaro", "Kandhkot", "Mir", "Jano", "Arazi", "Bhayo"],
    "Mianwali": ["Cantonment", "Gulshan", "Model Town", "Satellite Town", "Isa", "Khel", "Mitha", "Rang", "Sultan", "Wazir"],
    "Hafizabad": ["Cantonment", "Gulshan", "Sukheke", "Pindi Bhattian", "Jalal", "Kot", "Nakka", "Kharal", "Theh", "Chak"],
    "Jhelum": ["Cantonment", "Gulshan", "Ghar", "Dina", "Sohawa", "Pindora", "Kala", "Gujar", "Bhandar", "Sara-e-Alamgir"],
    "Mandi Bahauddin": ["Cantonment", "Gulshan", "Phalia", "Bhikhi", "Qadirabad", "Kuthiala", "Mong", "Sahiwal", "Kot", "Bhindar"],
    "Daska": ["Cantonment", "Gulshan", "Marala", "Kot", "Bajwa", "Cheema", "Lakhan", "Bhatti", "Goraya", "Sandhu"],
    "Narowal": ["Cantonment", "Gulshan", "Shakar", "Gulab", "Kot", "Chak", "Mala", "Sangat", "Dharar", "Khunda"],
    "Sheikhupura": ["Cantonment", "Gulshan", "Murid", "Manan", "Feroz", "Sangla", "Jand", "Manawala", "Safdar", "Chand"],
    "Khanewal": ["Cantonment", "Gulshan", "Kabir", "Mian", "Jahan", "Rai", "Kothi", "Shahi", "Shah", "Fazal"],
    "Vehari": ["Cantonment", "Gulshan", "Machhi", "Burewala", "Lodhran", "Kammar", "Mian", "Chak", "Makhdoom", "Rafique"],
    "Pakpattan": ["Cantonment", "Gulshan", "Arif", "Kot", "Malka", "Hanif", "Firoz", "Sadiq", "Iqbal", "Razzaq"],
    "Rajanpur": ["Cantonment", "Gulshan", "Kot", "Mithan", "Wazir", "Fazal", "Shah", "Gul", "Bahar", "Sultan"],
    "Lodhran": ["Cantonment", "Gulshan", "Dunyapur", "Jalal", "Kot", "Mian", "Sadiq", "Iqbal", "Raza", "Khalid"],
    "Chakwal": ["Cantonment", "Gulshan", "Kallar", "Bhaun", "Gujar", "Dudial", "Balkassar", "Chand", "Mang", "Sara"],
    "Attock": ["Cantonment", "Gulshan", "Hassan", "Jehan", "Fateh", "Tara", "Kamra", "Chach", "Jand", "Pindi"],
    "Kohat": ["Cantonment", "Gulshan", "Bahadur", "Jarma", "Bar", "Shah", "Gul", "Raza", "Khan", "Kot"],
    "Bannu": ["Cantonment", "Gulshan", "Miran", "Domail", "Mamash", "Kakki", "Sadda", "Baka", "Khel", "Mian"],
    "Charsadda": ["Cantonment", "Gulshan", "Tangi", "Pabbi", "Utman", "Shabqadar", "Daud", "Jang", "Khas", "Khan"],
    "Swat": ["Cantonment", "Saidu", "Bahrain", "Kalam", "Madyan", "Mingora", "Khwazakhela", "Charbagh", "Kanju", "Odigram"],
    "Dir": ["Cantonment", "Gulshan", "Timergara", "Balambat", "Maiden", "Wari", "Laram", "Khal", "Band", "Talar"],
    "Malakand": ["Cantonment", "Gulshan", "Batkhela", "Dargai", "Khar", "Aden", "Sawat", "Rang", "Mian", "Kot"],
    "Gilgit": ["Cantonment", "Gulshan", "Danyor", "Sultanabad", "Jutial", "Nagar", "Hunza", "Chilas", "Astore", "Skardu"],
    "Skardu": ["Cantonment", "Gulshan", "Sadpara", "Kardong", "Shigar", "Khaplu", "Kandia", "Damb", "Gamb", "Hassi"],
    "Chitral": ["Cantonment", "Gulshan", "Mastuj", "Booni", "Arandu", "Garam Chashma", "Ayun", "Brosh", "Lot", "Kot"],
    "Muzaffarabad": ["Cantonment", "Gulshan", "Chakkar", "Hattian", "Garhi", "Akhrian", "Nead", "Battal", "Palandri", "Manda"],
    "Mirpur (AK)": ["Cantonment", "Gulshan", "Dadyal", "Tanda", "Islamgarh", "Khammoo", "Chaksawari", "Ban", "Kot", "Bhera"],
    "Kotli": ["Cantonment", "Gulshan", "Charhoi", "Dheerkot", "Sehnsa", "Khurshid", "Tohid", "Sardar", "Sams", "Gul"],
    "Bhimber": ["Cantonment", "Gulshan", "Samahni", "Lakh", "Guli", "Kakuta", "Poonch", "Khamba", "Jat", "Tanda"],
    "Rawalakot": ["Cantonment", "Gulshan", "Hajira", "Khaigala", "Mong", "Bajri", "Trarkhel", "Pandi", "Sehra", "Jand"],
    "Tando Allahyar": ["Cantonment", "Gulshan", "Chambar", "Matli", "Miani", "Dhoron", "Nasarpur", "Khad", "Sayed", "Ali"],
    "Tando Muhammad Khan": ["Cantonment", "Gulshan", "Bagh", "Bulri", "Khar", "Gul", "Shah", "Mian", "Pir", "Sadiq"],
    "Dadu": ["Cantonment", "Gulshan", "Johi", "Mehar", "Khairpur", "Thul", "Karampur", "Naudero", "Miro", "Kot"],
    "Khairpur": ["Cantonment", "Gulshan", "Mir", "Nawab", "Gambat", "Bozdar", "Kot", "Diji", "Shah", "Raja"],
    "Jacobabad": ["Cantonment", "Gulshan", "Ghar", "Thul", "Shikarpur", "Larkana", "Kamber", "Miro", "Khan", "Dera"],
    "Shikarpur": ["Cantonment", "Gulshan", "Lakhi", "Garhi", "Kand", "Kot", "Mian", "Haji", "Pir", "Bhan"],
    "Sanghar": ["Cantonment", "Gulshan", "Shahpur", "Chamber", "Khipro", "Jhol", "Matiari", "Pithoro", "Bhan", "Raja"],
    "Matiari": ["Cantonment", "Gulshan", "Hala", "Saeed", "Bhit", "Shah", "Bhutto", "Kot", "Mian", "Jani"],
    "Jamshoro": ["Cantonment", "Gulshan", "Noori", "Kot", "Bhan", "Saeed", "Rashid", "Qasim", "Ali", "Gul"],
    "Badin": ["Cantonment", "Gulshan", "Tando", "Gul", "Mian", "Kot", "Shah", "Raza", "Sadiq", "Fazal"],
    "Thatta": ["Cantonment", "Gulshan", "Makli", "Sujawal", "Keti", "Bhan", "Shah", "Ghar", "Kot", "Pir"],
    "Naushahro Feroze": ["Cantonment", "Gulshan", "Mehrabpur", "Bozdar", "Moro", "Kandiaro", "Halani", "Sakrand", "Daur", "Bhan"],
    "Kambar": ["Cantonment", "Gulshan", "Miro", "Khan", "Kot", "Shah", "Gul", "Mian", "Raza", "Sadiq"],
    "Kandhkot": ["Cantonment", "Gulshan", "Kashmore", "Ghotki", "Daharki", "Ubaro", "Mir", "Jano", "Bhayo", "Arazi"],
    "Gharo": ["Cantonment", "Gulshan", "Keti", "Bhan", "Shah", "Pir", "Mian", "Kot", "Gul", "Raza"],
    "Mirpur Mathelo": ["Cantonment", "Gulshan", "Ubaro", "Ghotki", "Daharki", "Kandhkot", "Mir", "Jano", "Bhayo", "Arazi"],
    "Kotri": ["Cantonment", "Gulshan", "Saeed", "Bhan", "Shah", "Kot", "Mian", "Gul", "Raza", "Sadiq"],
    "Sehwan Sharif": ["Cantonment", "Gulshan", "Bhan", "Shah", "Pir", "Kot", "Mian", "Gul", "Raza", "Sadiq"],
    "Moro": ["Cantonment", "Gulshan", "Sakrand", "Daur", "Bhan", "Shah", "Kot", "Mian", "Gul", "Raza"],
    "Mehar": ["Cantonment", "Gulshan", "Johi", "Dadu", "Thul", "Karampur", "Naudero", "Miro", "Khan", "Kot"],
    "Ratodero": ["Cantonment", "Gulshan", "Bakrani", "Dokri", "Sikandarabad", "Miro", "Khan", "Kamber", "Larkana", "Chandka"],
    "Kashmore": ["Cantonment", "Gulshan", "Kandhkot", "Ghotki", "Daharki", "Ubaro", "Mir", "Jano", "Bhayo", "Arazi"],
    "Pano Aqil": ["Cantonment", "Gulshan", "Shahdad", "Rohri", "Sukkur", "Kandhkot", "Kashmore", "Ghotki", "Daharki", "Ubaro"],
    "Gambat": ["Cantonment", "Gulshan", "Bozdar", "Khairpur", "Mir", "Nawab", "Kot", "Diji", "Shah", "Raja"],
    "Mianwali": ["Cantonment", "Gulshan", "Isa", "Khel", "Mitha", "Rang", "Sultan", "Wazir", "Kot", "Chak"],
    "Bhakar": ["Cantonment", "Gulshan", "Darya", "Khan", "Kot", "Shah", "Mian", "Gul", "Raza", "Sadiq"],
    "Layyah": ["Cantonment", "Gulshan", "Chak", "Mian", "Kot", "Shah", "Gul", "Raza", "Sadiq", "Fazal"],
    "Muzaffargarh": ["Cantonment", "Gulshan", "Kot", "Mubarak", "Choti", "Kohlu", "Zindani", "Deen", "Sadiq", "Jalal"],
    "Jampur": ["Cantonment", "Gulshan", "Rajanpur", "Kot", "Mithan", "Wazir", "Fazal", "Shah", "Gul", "Sultan"],
    "Ahmedpur": ["Cantonment", "Gulshan", "Chowk", "Hasilpur", "Uch", "Dera", "Nawab", "Kot", "Mian", "Shah"],
    "Hasilpur": ["Cantonment", "Gulshan", "Ahmedpur", "Chowk", "Uch", "Dera", "Nawab", "Kot", "Mian", "Shah"],
    "Uch Sharif": ["Cantonment", "Gulshan", "Ahmedpur", "Hasilpur", "Chowk", "Dera", "Nawab", "Kot", "Mian", "Shah"],
    "Dera Nawab": ["Cantonment", "Gulshan", "Ahmedpur", "Hasilpur", "Chowk", "Uch", "Dera", "Nawab", "Kot", "Mian"],
    "Khuzdar": ["Cantonment", "Gulshan", "Wadh", "Mulla", "Kot", "Shah", "Gul", "Raza", "Sadiq", "Fazal"],
    "Loralai": ["Cantonment", "Gulshan", "Kohlu", "Mekhtar", "Duki", "Bori", "Kot", "Shah", "Gul", "Raza"],
    "Zhob": ["Cantonment", "Gulshan", "Mekhtar", "Kohlu", "Duki", "Bori", "Kot", "Shah", "Gul", "Raza"],
    "Chaman": ["Cantonment", "Gulshan", "Killa", "Abdullah", "Spin", "Gul", "Kot", "Shah", "Raza", "Sadiq"],
    "Gwadar": ["Cantonment", "Gulshan", "Pasni", "Ormara", "Turbat", "Dasht", "Kech", "Hoshab", "Mand", "Suntsar"],
    "Panjgur": ["Cantonment", "Gulshan", "Turbat", "Dasht", "Kech", "Hoshab", "Mand", "Suntsar", "Gabd", "Kalar"]
}


ALL_GEOGRAPHIES = {
    "Turkey": TURKIYE_GEOGRAPHY,
    "USA": US_GEOGRAPHY,
    "UK": UK_GEOGRAPHY
}
